basic = [
    "7zip",
    "Maple-Mono-NF-CN",
    "aria2",
    "affine",
    "binaryen",
    "bun",
    "chsrc",
    "clangd",
    "cmake",
    "cwrsync",
    "dark",
    "dbeaver",
    "deno",
    "ditto",
    "fastfetch",
    "ffmpeg",
    "fnm",
    "fzf",
    "git",
    "go",
    "helix",
    "innounp",
    "llvm",
    "magic-wormhole",
    "miktex",
    "mingw",
    "motrix",
    "nasm",
    "openssl",
    "perl",
    "picgo",
    "postgresql",
    "restic",
    "scoop-search",
    "sudo",
    "tailscale",
    "uv",
    "vscode",
    "wabt",
    "wget",
    "wireshark",
    "xmake",
    "yaak",
    "zig",
]
hold = [
    "bun",
    "deno",
    "go",
    "llvm",
    "nu",
    "openssl",
    "postgresql",
    "wireshark",
]
